DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER REFERENCES menus(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  details VARCHAR(255) NOT NULL,
  price_cents INTEGER NOT NULL,
  active BOOLEAN
);