DROP TABLE IF EXISTS cart CASCADE;
CREATE TABLE cart (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);
-- DROP TABLE IF EXISTS carts CASCADE;
-- CREATE TABLE carts (
-- id SERIAL PRIMARY KEY NOT NULL,
-- created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
-- updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
