DROP TABLE IF EXISTS cart_items CASCADE;
CREATE TABLE cart_items (
id SERIAL PRIMARY KEY NOT NULL,
cart_id INTEGER REFERENCES cart(id) ON DELETE CASCADE,
item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
quantity INTEGER DEFAULT 1
);
